-- =========================================================================
-- Life OS — Character Progression Schema (Phase 1)
-- =========================================================================

-- 1. TITLE TABLE
CREATE TABLE title (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(1000),
    icon VARCHAR(255),
    required_level INT NOT NULL DEFAULT 1
);

-- 2. CHARACTER TABLE
CREATE TABLE character (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE,
    current_level INT NOT NULL DEFAULT 1,
    total_xp INT NOT NULL DEFAULT 0,
    title_id BIGINT REFERENCES title(id) ON DELETE SET NULL,
    -- embedded stats
    knowledge INT NOT NULL DEFAULT 10,
    discipline INT NOT NULL DEFAULT 10,
    focus INT NOT NULL DEFAULT 10,
    endurance INT NOT NULL DEFAULT 10,
    strength INT NOT NULL DEFAULT 10,
    creativity INT NOT NULL DEFAULT 10,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. SKILL CATEGORY TABLE
CREATE TABLE skill_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(1000)
);

-- 4. SKILL TABLE
CREATE TABLE skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES skill_category(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(1000),
    icon VARCHAR(255),
    display_order INT NOT NULL DEFAULT 0
);

-- 5. USER SKILL TABLE (Progress tracking)
CREATE TABLE user_skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL REFERENCES character(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES skill(id) ON DELETE CASCADE,
    current_level INT NOT NULL DEFAULT 1,
    total_xp INT NOT NULL DEFAULT 0,
    unlocked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_character_skill UNIQUE (character_id, skill_id)
);

-- 6. XP HISTORY TABLE
CREATE TABLE xp_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL REFERENCES character(id) ON DELETE CASCADE,
    skill_id BIGINT REFERENCES skill(id) ON DELETE SET NULL,
    xp INT NOT NULL,
    source VARCHAR(255) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- INDEXES
CREATE INDEX idx_character_user_id ON character(user_id);
CREATE INDEX idx_user_skill_char_skill ON user_skill(character_id, skill_id);
CREATE INDEX idx_xp_history_char_created ON xp_history(character_id, created_at);
CREATE INDEX idx_skill_category_id ON skill(category_id);
CREATE INDEX idx_title_required_level ON title(required_level);

-- =========================================================================
-- Seed Initial Data
-- =========================================================================

-- Seed Titles
INSERT INTO title (name, description, icon, required_level) VALUES
('The Beginner', 'Starting path on the digital progression journey.', 'icon-beginner', 1),
('Backend Apprentice', 'Has successfully completed foundational Java tasks.', 'icon-apprentice', 10),
('Spring Explorer', 'Understands the depths of Spring Boot and REST paradigms.', 'icon-explorer', 20),
('Deployment Master', 'Deploys systems confidently without breaking prod.', 'icon-master', 30),
('The Architect', 'Designs systems that last ten years.', 'icon-architect', 40);

-- Seed Skill Categories
INSERT INTO skill_category (name, description) VALUES
('Backend', 'Server side applications, DBs, and caching structures.'),
('DevOps', 'CI/CD, deployment orchestration, and cloud infrastructure.'),
('Security', 'OAuth2, OpenID Connect, network security, and cryptography.'),
('Adventure', 'Outdoors, travel, and exploration activities.'),
('Entertainment', 'Movies, reading, gaming, and mental relaxation.'),
('Health', 'Physical fitness, training, nutrition, and recovery.'),
('Finance', 'Budgets, savings, investments, and wealth management.'),
('Learning', 'Books, certificates, online classes, and new skills acquisition.');

-- Seed Initial Skills
INSERT INTO skill (category_id, name, description, icon, display_order) VALUES
((SELECT id FROM skill_category WHERE name = 'Backend'), 'Java Programming', 'Object-oriented programming using Java language paradigms.', 'icon-java', 1),
((SELECT id FROM skill_category WHERE name = 'Backend'), 'Spring Boot Framework', 'Creating production-ready backend applications using Spring Boot.', 'icon-springboot', 2),
((SELECT id FROM skill_category WHERE name = 'Backend'), 'PostgreSQL Database', 'Relational database management, querying, and schema optimization.', 'icon-postgres', 3),
((SELECT id FROM skill_category WHERE name = 'DevOps'), 'Docker Containers', 'Containerization and isolation of backend services.', 'icon-docker', 1),
((SELECT id FROM skill_category WHERE name = 'Security'), 'OAuth2 Security', 'Implementation of secure authentication protocols.', 'icon-oauth2', 1),
((SELECT id FROM skill_category WHERE name = 'Learning'), 'Domain-Driven Design', 'Designing software around domain models and bounded contexts.', 'icon-ddd', 1),
((SELECT id FROM skill_category WHERE name = 'Learning'), 'Clean Architecture', 'Structuring code base for long-term maintainability and testing.', 'icon-clean-arch', 2);
