package com.lifeos.project.enums;

public enum ActivityAction {
    CREATE_PROJECT,
    UPDATE_PROJECT,
    DELETE_PROJECT,
    ADD_MEMBER,
    UPDATE_MEMBER,
    REMOVE_MEMBER,
    CREATE_BOARD,
    UPDATE_BOARD,
    DELETE_BOARD,
    CREATE_COLUMN,
    UPDATE_COLUMN,
    MOVE_COLUMN,
    DELETE_COLUMN,
    CREATE_TASK,
    UPDATE_TASK,
    MOVE_TASK,
    DELETE_TASK,
    ADD_COMMENT,
    DELETE_COMMENT,
    ADD_ATTACHMENT,
    DELETE_ATTACHMENT
}
